name: "Qualified vLEI Issuer Identifer vLEI Credential"
description: Feedback
title: "A concise description"
assignees:
  - kmckenna-gleif
body:
  - type: markdown
    attributes:
      value: | 
        2023-08-30_verifiable-LEI-(vLEI)-Ecosystem-Governance-Framework-Qualified-vLEI-Issuer-Identifer-vLEI-Credential-Governance-Framework_v1.2_final.pdf
  - type: dropdown
    id: document
    attributes:
      label: Document
      options:
        - Qualified-vLEI-Issuer-Identifer-vLEI-Credential-Governance-Framework
      default: 0
  - type: input
    id: section
    attributes:
      label: Section Name
      description: Section title from document
    validations:
      required: true
  - type: input
    id: row-number
    attributes:
      label: Row number
      description: Row number from document
    validations:
      required: true
  - type: textarea
    id: question-comment
    attributes:
      label: Question/Comment
      description: Please suggest a proposed update/edit that would resolve your question or comment.
    validations:
      required: true